#!/bin/bash

dir=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
cd $dir

PROFILE=${1:-default}

echo "Setting up profile $PROFILE..."

for COMPONENT in $(cat profiles/$PROFILE); do
    COMPONENT="${COMPONENT//[$'\t\r\n ']}"
    echo "Setting up component $COMPONENT..."
    ./require $COMPONENT
done

echo "Done"
