#!/bin/bash

mkdir -p $HOME/.bashrc.d
mkdir -p $HOME/bin

if ! grep --quiet "Source custom scripts" "$HOME/.bashrc"; then
cat >> $HOME/.bashrc <<EOF

# Source custom scripts
export SETUP_PATH="$PWD"
for f in \$HOME/.bashrc.d/*; do
   . "\$f"
done
EOF
fi

cp --force files/self.sh $HOME/.bashrc.d/self.sh
cp --force files/mem.sh $HOME/.bashrc.d/mem.sh
