#!/bin/bash

require bashrc
require git

HERE=$(pwd)

echo "Installing packages..."
if [[ -s $(which dnf) ]]; then
    sudo dnf install cryptsetup btrfs-tools
elif [[ -s $(which apt) ]]; then
    sudo apt-get install cryptsetup btrfs-tools
else
    echo "OS not supported."
fi

echo "Installing cryptmount..."
mkdir -p $HOME/git
cd $HOME/git
if [[ ! -d cryptmount ]]; then
    git clone https://github.com/eblade/cryptmount.git
fi

cd $HERE

ln -s --force files/cryptmount.sh $HOME/.bashrc.d/cryptmount.sh
