#!/bin/bash

HERE="$(pwd)"

require bashrc

sudo dnf install fish

FISH_CONFIG_DIR="$HOME/.config/fish"
mkdir -p "$FISH_CONFIG_DIR/conf.d"
mkdir -p "$FISH_CONFIG_DIR/functions"
ln -s --force "$HERE/files/config.fish" "$FISH_CONFIG_DIR/"
ln -s --force "$HERE/files/fish_variables" "$FISH_CONFIG_DIR/"
ln -s --force "$HERE/files/fish_command_timer.fish" "$FISH_CONFIG_DIR/conf.d/"
ln -s --force "$HERE/files/fish_prompt.fish" "$FISH_CONFIG_DIR/functions/"
