#!/bin/bash

git config --global user.email "johan@egneblad.se"
git config --global user.name "Johan Egneblad"
git config --global push.default simple

git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status
