#!/bin/bash

require bashrc

ln -s --force $PWD/files/markdownpreview.sh $PWD/files/listings-setup.tex $HOME/.bashrc.d/

if [[ -s $(which dnf) ]]; then
    sudo dnf install pandoc texlive-base texlive-xcolor
elif [[ -s $(which apt) ]]; then
    sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-recommended latex-xcolor --no-install-recommends
else
    echo "OS not supported."
fi
