#!/bin/bash

require bashrc
require git
require libtool

HERE=$(pwd)

# Checkout neovim or pull the latest version
COMPILE="yes"
mkdir -p $HOME/git
cd $HOME/git
if [[ ! -d neovim ]]; then
    git clone https://github.com/neovim/neovim.git
    cd neovim
else
    cd neovim
    RESPONSE=`git pull`
    if [ "$RESPONSE" == "Already up-to-date." ]; then
        echo "Neovim check-out up-to-date."
        COMPILE="no"
    fi
fi

# Build and install neovim
if [ "$COMPILE" == "yes" ]; then
    make
    sudo make install
else
    echo "No need to re-compile."
fi

# Account for the new config paths
mkdir -p $HOME/.config/nvim

cd $HERE
require vimrc
cp -f $HOME/.vimrc $HOME/.config/nvim/init.vim

# Install plugins for via vundle neovim as well
nvim +PluginInstall +qall
