#!/bin/bash

require bashrc
require git
require libtool

HERE=$(pwd)

# Checkout neovim or pull the latest version
mkdir -p $HOME/git
cd $HOME/git
if [[ ! -d neovim ]]; then
    git clone https://github.com/neovim/neovim.git
    cd neovim
else
    cd neovim
    git pull
fi

# Build and install neovim
make
sudo make install

# Account for the new config paths
mkdir -p $HOME/.config/nvim

cd $HERE
require vimrc
cp -f $HOME/.vimrc $HOME/.config/nvim/init.vim
cp -rf $HOME/.vim/* $HOME/.config/nvim/

# Add some terminal-mode specific config that would break old vim
cat >> $HOME/.config/nvim/init.vim <<EOF
" Inserted especially for neovim by setup

:tnoremap <A-h> <C-\><C-n><C-w>h
:tnoremap <A-j> <C-\><C-n><C-w>j
:tnoremap <A-k> <C-\><C-n><C-w>k
:tnoremap <A-l> <C-\><C-n><C-w>l
:nnoremap <A-h> <C-w>h
:nnoremap <A-j> <C-w>j
:nnoremap <A-k> <C-w>k
:nnoremap <A-l> <C-w>l
EOF
