#!/bin/bash

require bashrc

HERE="$(pwd)"

if [[ ! $(which pip) ]]; then
    echo "Installing pip..."
    cd /tmp
    wget https://bootstrap.pypa.io/get-pip.py
    sudo python get-pip.py
fi

echo "Upgrading pip..."
sudo pip install --upgrade pip

ln -s --force $HERE/files/python-aliases.sh $HOME/.bashrc.d/python-aliases.sh
