#!/bin/bash

require bashrc


SVN="$HOME/svn"

# Checking out ssh_nat from SVN
mkdir -p $SVN
cd "$SVN"

if [[ -d ssh_nat ]]; then
    cd ssh_nat
    svn up
else
    svn co svn://svn/ssh_nat/trunk ssh_nat
fi

# Linking
ln -fs "$SVN/ssh_nat/bin/ssh_nat" "$HOME/bin/ssh_nat"
ln -fs "$SVN/ssh_nat/cfg" "$HOME/.ssh_nat"
