#!/bin/bash

require bashrc
require git

# Checking out ssh_nat from saint
cd "$HOME/git"

if [[ -d ssh_nat ]]; then
    cd ssh_nat
    git pull --rebase
else
    git clone saint:git/ssh_nat.git
fi

# Linking
ln -fs "$HOME/git/ssh_nat/bin/ssh_nat" "$HOME/bin/ssh_nat"
ln -fs "$HOME/git/ssh_nat/cfg" "$HOME/.ssh_nat"
