#!/bin/bash

sudo apt install nodejs npm

# Some npm packages think that "nodejs" is called just "node"
if [[ ! -e /usr/bin/node ]]; then
    sudo ln -s /usr/bin/nodejs /usr/bin/node
fi

LOCAL_USER="$USER"
LOCAL_HOME="$HOME"
if [[ -e $HOME/.npm ]]; then
    echo "Fixing permissions for ~/.npm"
    sudo chown -R $LOCAL_USER:$LOCAL_USER $LOCAL_HOME/.npm
fi
