#!/bin/bash

require git

HERE="$(pwd)"

echo "Linking .vimrc file to $HOME..."
ln -s --force $HERE/files/dot-vimrc $HOME/.vimrc

echo "Setting up $HOME/.vim..."
mkdir -p "$HOME/.vim"

VUNDLEPATH="$HOME/.vim/bundle/Vundle.vim"
if [ ! -d "$VUNDLEPATH" ]; then
    echo "Installing Vundle..."
    git clone https://github.com/VundleVim/Vundle.vim.git "$VUNDLEPATH"
else
    echo "Upgrading Vundle..."
    cd "$VUNDLEPATH"
    git pull
fi
vim +PluginInstall +qall
