#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "Root required"
    exit 1
fi

# monkey is part of python-tools
require python-tools
. /root/.bashrc

HERE=$(pwd)

# fetch and unpack cora APA packages
mkdir -p /root/vme/packages
cd /root/vme/packages
if [[ ! -e ardome5-packages.tar ]]; then
    curl http://releases.ardendo.se/builds/mam/ardome5-packages/ardome5-packages-5_11_0-B17.tar > ardome5-packages.tar
    tar xf ardome5-packages.tar
fi

# extra meta packages to make the graph complete
cp $HERE/files/ardome-link.apa /root/vme/packages/
cp $HERE/files/demctl-link.apa /root/vme/packages/

# fetch and unpack the installer
mkdir -p /root/vme/installer
cd /root/vme/installer
if [[ ! -e installer.tar ]]; then
    curl http://releases.ardendo.se/builds/mam/ardome5-installer-vme/ardome5-installer-vme-5_11_0-B19.tar > installer.tar
    tar xf installer.tar
fi

# copy default scamp config needed by monkey
mkdir -p /var/ardendo/conf/scamp
cp users groups /var/ardendo/conf/scamp

# set up root key (needed for demctl)
if [[ -e /root/.ssh/id_dsa.pub ]]; then
    cp /root/.ssh/id_dsa.pub /root/.ssh/authorized_keys
else
    cp /root/.ssh/id_rsa.pub /root/.ssh/authorized_keys
fi
ssh-keyscan -t rsa,dsa `hostname` >> /root/.ssh/known_hosts

# setup users and install all APAs
monkey setup
monkey install /root/vme/installer/*.apa
monkey install /root/vme/packages/*.apa
monkey install /root/vme/packages/rhel6/*.apa
monkey apply
