#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    echo "Root required"
    exit 1
fi

# monkey is part of python-tools
require python-tools
. /root/.bashrc

# Rename MODUTILS::Exception links
for LINK_TARGET in $(monkey linktargets modutils-ardome5); do
    OLD_LINK="$LINK_TARGET/lib/perl/MODUTILS/exception.pm"
    NEW_LINK="$LINK_TARGET/lib/perl/MODUTILS/Exception.pm"

    if [[ ! -h "$NEW_LINK" ]]; then
        mv "$OLD_LINK" "$NEW_LINK"
    fi
done
