#!/bin/bash

function sgp {
    read -srp 'Password: ' master
    local domain=$(echo $1 | tr A-Z a-z)
    local length=${2:-10}

    hash=$master:$domain
    >&2 echo ""

    i=0
    while true
    do
        hash=$(echo -n "$hash" | openssl md5 -binary | base64 | tr +/= 98A)
        i=$(($i + 1))
        if [ $i -lt 10 ]
        then
            continue
        fi
        valid=$(echo "${hash:0:$length}" | grep -E '^[a-z]' | grep -E '.[A-Z]' | grep -E '.[0-9]' )
        if [ "$valid" != "" ]
        then
            break
        fi
    done
    echo ${hash:0:$length}
}

if [ -e "$HOME/.sgpargs" ]; then
    SGPARGS=$(cat "$HOME/.sgpargs")
else
    SGPARGS=$(hostname --short)
fi

sgp $SGPARGS
