#!/bin/bash

RESOURCE_NAME='seagate'
#RESOURCE_PATH=/dev/disk/by-id/ata-ST2000LM007-1R8174_WCC1BA11-part1
RESOURCE_PATH='/dev/disk/by-id/usb-Seagate_Expansion_NA83ZD6M-0:0-part1'
MOUNT_POINT=/run/media/$LOGNAME/seagate
