#!/bin/bash

# Deletes all files and folders in the Download folder
# older than two weeks.

find ~/Downloads -type d -mtime +14 -exec rm -rf {} \;
find ~/Downloads -type f -mtime +14 -exec rm -f {} \;
