#!/usr/bin/env python3

# Convert what's on STDIN on Hex (0xAF35DE... or just AF35DE) into bytes AF 35 DE.
# Push the binary result to STDOUT. Also print the printable characters among the
# 50 first bytes to STDERR.

import sys

first = True

while True:
    data = sys.stdin.buffer.read(1024)
    if not data:
        break
    data = data.replace(b'\n', b'')
    if data[0:2] == b'0x':
        data = data[2:]
    bdata = bytes(int(data[i:i+2], 16) for i in range(0, len(data), 2))
    sys.stdout.buffer.write(bdata)
    if first:
        sys.stderr.write(''.join(chr(b) for b in bdata[:50] if b >= 31 and b <= 132) + '\n')
    first = False
