#!/usr/bin/env python3

import sys


unix = 0
windows = 0

endings = []


for line in sys.stdin.readlines():
    if line.endswith('\r\n'):
        windows += 1
    elif line.endswith('\n'):
        unix += 1


print("UNIX       (LF): %i" % unix)
print("Windows (CR+LF): %i" % windows)
